atlas.system={darwin-generator-nodejs-system}
atlas.subsystem={darwin-generator-nodejs-sub-system}
atlas.application.acronym={appcli}
atlas.application.code={darwin-generator-nodejs-application}
atlas.subapplication.code={darwin-generator-nodejs-sub-application}
